from adafruit_hid.keycode import Keycode

KEYMAP_TRANSLATE = {
    '': (),
    'a': Keycode.A,
    'b': Keycode.B,
    'c': Keycode.C,
    'd': Keycode.D,
    'e': Keycode.E,
    'f': Keycode.F,
    'g': Keycode.G,
    'h': Keycode.H,
    'i': Keycode.I,
    'j': Keycode.J,
    'k': Keycode.K,
    'l': Keycode.L,
    'm': Keycode.M,
    'n': Keycode.N,
    'o': Keycode.O,
    'p': Keycode.P,
    'q': Keycode.Q,
    'r': Keycode.R,
    's': Keycode.S,
    't': Keycode.T,
    'u': Keycode.U,
    'v': Keycode.V,
    'w': Keycode.W,
    'x': Keycode.X,
    'y': Keycode.Y,
    'z': Keycode.Z,
    'A': (Keycode.SHIFT, Keycode.A),
    'B': (Keycode.SHIFT, Keycode.B),
    'C': (Keycode.SHIFT, Keycode.C),
    'D': (Keycode.SHIFT, Keycode.D),
    'E': (Keycode.SHIFT, Keycode.E),
    'F': (Keycode.SHIFT, Keycode.F),
    'G': (Keycode.SHIFT, Keycode.G),
    'H': (Keycode.SHIFT, Keycode.H),
    'I': (Keycode.SHIFT, Keycode.I),
    'J': (Keycode.SHIFT, Keycode.J),
    'K': (Keycode.SHIFT, Keycode.K),
    'L': (Keycode.SHIFT, Keycode.L),
    'M': (Keycode.SHIFT, Keycode.M),
    'N': (Keycode.SHIFT, Keycode.N),
    'O': (Keycode.SHIFT, Keycode.O),
    'P': (Keycode.SHIFT, Keycode.P),
    'Q': (Keycode.SHIFT, Keycode.Q),
    'R': (Keycode.SHIFT, Keycode.R),
    'S': (Keycode.SHIFT, Keycode.S),
    'T': (Keycode.SHIFT, Keycode.T),
    'U': (Keycode.SHIFT, Keycode.U),
    'V': (Keycode.SHIFT, Keycode.V),
    'W': (Keycode.SHIFT, Keycode.W),
    'X': (Keycode.SHIFT, Keycode.X),
    'Y': (Keycode.SHIFT, Keycode.Y),
    'Z': (Keycode.SHIFT, Keycode.Z),
    '0': Keycode.ZERO,
    '1': Keycode.ONE,
    '2': Keycode.TWO,
    '3': Keycode.THREE,
    '4': Keycode.FOUR,
    '5': Keycode.FIVE,
    '6': Keycode.SIX,
    '7': Keycode.SEVEN,
    '8': Keycode.EIGHT,
    '9': Keycode.NINE,
    ')': (Keycode.SHIFT, Keycode.NINE),
    '!': (Keycode.SHIFT, Keycode.ONE),
    '@': (Keycode.SHIFT, Keycode.TWO),
    '#': (Keycode.SHIFT, Keycode.THREE),
    '$': (Keycode.SHIFT, Keycode.FOUR),
    '%': (Keycode.SHIFT, Keycode.FIVE),
    '^': (Keycode.SHIFT, Keycode.SIX),
    '&': (Keycode.SHIFT, Keycode.SEVEN),
    '*': (Keycode.SHIFT, Keycode.EIGHT),
    '(': (Keycode.SHIFT, Keycode.ZERO),
    '-': Keycode.MINUS,
    '_': (Keycode.SHIFT, Keycode.MINUS),
    '=': Keycode.EQUALS,
    '+': (Keycode.SHIFT, Keycode.EQUALS),
    ';': Keycode.SEMICOLON,
    ':': (Keycode.SHIFT, Keycode.SEMICOLON),
    ' ': Keycode.SPACE,
    '[': Keycode.LEFT_BRACKET,
    '{': (Keycode.SHIFT, Keycode.LEFT_BRACKET),
    ']': Keycode.RIGHT_BRACKET,
    '}': (Keycode.SHIFT, Keycode.RIGHT_BRACKET),
    '`': Keycode.GRAVE_ACCENT,
    '~': (Keycode.SHIFT, Keycode.GRAVE_ACCENT),
    '/': Keycode.FORWARD_SLASH,
    '\\': Keycode.BACKSLASH,
    '.': Keycode.PERIOD,
    ',': Keycode.COMMA,
    "'": Keycode.QUOTE,
    '"': (Keycode.SHIFT, Keycode.QUOTE),
    '<': (Keycode.SHIFT, Keycode.COMMA),
    '>': (Keycode.SHIFT, Keycode.PERIOD), 
    '?': (Keycode.SHIFT, Keycode.FORWARD_SLASH),
    '|': (Keycode.SHIFT, Keycode.BACKSLASH),

    '_entr': Keycode.ENTER,
    '_left': Keycode.LEFT_ARROW,
    '_rght': Keycode.RIGHT_ARROW,
    '_up': Keycode.UP_ARROW,
    '_down': Keycode.DOWN_ARROW,
    '_home': Keycode.HOME,
    '_end': Keycode.END,
    '_bksp': Keycode.BACKSPACE,
    '_tab': Keycode.TAB,
    '_shft': Keycode.SHIFT,
    '_ctrl': Keycode.CONTROL,
    '_gui': Keycode.WINDOWS,
    '_rctrl': Keycode.RIGHT_CONTROL,
    '_pgup': Keycode.PAGE_UP,
    '_pgdn': Keycode.PAGE_DOWN,
    '_esc': Keycode.ESCAPE,
    '_del': Keycode.DELETE,
    '_ins': Keycode.INSERT,
    '_caps': Keycode.CAPS_LOCK,
    '_prtsc': Keycode.PRINT_SCREEN,
    # '_copy': Keycode.COPY,
    # '_paste': Keycode.PASTE,
    # '_cut': Keycode.CUT,
    # '_undo': Keycode.UNDO,
    # '_redo': Keycode.REDO,
    # '_find': Keycode.FIND,

    '_mbt1': None,
    '_mbt2': None,
    '_mbt3': None,
    '_scup': None,
    '_scdn': None,

    '_f1': Keycode.F1,
    '_f2': Keycode.F2,
    '_f3': Keycode.F3,
    '_f4': Keycode.F4,
    '_f5': Keycode.F5,
    '_f6': Keycode.F6,
    '_f7': Keycode.F7,
    '_f8': Keycode.F8,
    '_f9': Keycode.F9,
    '_f10': Keycode.F10,
    '_f11': Keycode.F11,
    '_f12': Keycode.F12,

    '_alta': (Keycode.LEFT_ALT, Keycode.TAB),
    '_salta': (Keycode.LEFT_ALT, Keycode.LEFT_SHIFT, Keycode.TAB),
}

# OTHERS = ( uinput.REL_X,
#            uinput.REL_Y,
#            uinput.REL_WHEEL,)
# UINPUT_ACTIVATE = set()
# for val in UINPUT_TRANSLATE.values():
#     if val == ():
#         continue
#     if isinstance(val[0], (list, tuple)):
#         UINPUT_ACTIVATE.update(val)
#     else:
#         UINPUT_ACTIVATE.add(val)
# UINPUT_ACTIVATE.update(OTHERS)

# UINPUT_ACTIVATE = list(sorted(UINPUT_ACTIVATE))
